# Generated by Django 4.2.2 on 2023-07-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favorite_posts',
            field=models.ManyToManyField(blank=True, related_name='favorite_by', to='apps.post'),
        ),
    ]
