# Generated by Django 4.2.2 on 2023-07-09 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_account_favorite_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='favorite_posts',
            new_name='favorite_courses',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_image',
        ),
    ]
