# Generated by Django 4.2.2 on 2023-07-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_rename_post_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.IntegerField(choices=[(4, '4'), (2, '2'), (0, '0')], default=0),
        ),
    ]
