# Generated by Django 4.2.2 on 2023-07-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_course_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='body',
            new_name='professor',
        ),
    ]
