# Generated by Django 4.2.2 on 2023-07-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_rename_body_course_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.TextField(choices=[('----', '----'), ('Faculty of Environment and Information Studies', 'Faculty of Environment and Information Studies'), ('Faculty of Policy Management', 'Faculty of Policy Management'), ('Faculty of Media and Governance', 'Faculty of Media and Governance')], default='----'),
        ),
    ]
